### PR TITLE
Style Updates - See Comments

### PR DESCRIPTION
**Pull request by corumgold**
Move links into email sign in component and style with icons

### CODE REVIEW

**Comment by corumgold** [comment]
1. Style oAuth Links

**Comment by corumgold** [comment]
2. Fix the navbar on mobile view

**Comment by corumgold** [comment]
3. Fix heights for main page and header/footer

**Comment by corumgold** [comment]
4. Fix matches overflowing in mobile view

**Review by echos-echo — APPROVED** [review]

**Pull request merged**
